### ISSUE TITLE
请问你们是在哪学习的html代码？

### ISSUE THREAD

**Issue by mcheping520** [Sean537/sean537.github.io#2]

**Comment by MinShpe** [comment]
我是外挂

**Comment by Sean537** [comment]
刚开始是知乎，后面全面转向CSDN

**Comment by mcheping520** [comment]
> 刚开始是知乎，后面全面转向CSDN

最好不要在CSDN学习，可以在菜鸟教程学习

我给你们推荐一个抖音up主：[python导师胖虎](https://www.douyin.com/user/MS4wLjABAAAAIMo71jNbImMxeyGX7LQdC3qH7VcKlTKOGm5_HmgmaT2jwHlKChUEWvyJldDDqlJP)

你们可以看看他的视频，也可以结合菜鸟教程学习

**Comment by MinShpe** [comment]
> 刚开始是知乎，后面全面转向CSDN

您是没听过最大程度误导人类的编程网站csdn啊

**Comment by MCheping8108** [comment]
> # 在你妈屁眼里学的 臭傻逼

别骂，他们是小学生，而且这里是GitHub
